# Generated by Django 5.0.7 on 2024-07-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bazaarblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
    ]
